apiVersion: sourceplane.io/v1alpha1
kind: ComponentSchema
metadata:
  name: terraform-component
spec:
  type: terraform
  schema:
    $schema: http://json-schema.org/draft-07/schema#
    title: Terraform Component
    type: object
    required:
      - name
      - type
      - parameters
    properties:
      name:
        type: string
      type:
        type: string
        const: terraform
      parameters:
        type: object
        required:
          - stackName
          - terraformDir
          - terraformVersion
        properties:
          awsAccountId:
            type: string
            description: AWS account ID hosting the GitHub-OIDC role this component assumes
          awsRegion:
            type: string
          lane:
            type: string
          namespace:
            type: string
          namespacePrefix:
            type: string
          orgName:
            type: string
          owner:
            type: string
          repo:
            type: string
          stackName:
            type: string
          terraformDir:
            type: string
          terraformVersion:
            type: string
        additionalProperties: true
    additionalProperties: true
