apiVersion: sourceplane.io/v1alpha1
kind: ExecutionProfile
metadata:
  name: terraform-plan-only
spec:
  description: PR Terraform plan with no-lock flag for non-mutating preview

  jobs:
    terraform:
      includeCapabilities:
        - terraform.setup
        - terraform.aws-credentials
        - terraform.env
        - terraform.context
        - terraform.fmt
        - terraform.init
        - terraform.workspace
        - terraform.validate
        - terraform.plan
